-- Sample Tour Data for Tour Management System
-- Đảm bảo rằng bạn đã có categories và partners trước khi chạy script này

-- Insert sample tours
INSERT INTO tours (
    title, 
    short_description, 
    description, 
    price, 
    discounted_price, 
    duration_days, 
    duration_nights, 
    max_participants, 
    min_participants,
    difficulty_level,
    status,
    is_featured,
    featured_image_url,
    gallery_images,
    included_services,
    excluded_services,
    cancellation_policy,
    terms_conditions,
    category_id,
    created_at,
    updated_at
) VALUES 
-- Tour 1: Hạ Long Bay
('Du thuyền Hạ Long Bay 2 ngày 1 đêm', 
'Khám phá vẻ đẹp kỳ vĩ của vịnh Hạ Long với du thuyền sang trọng',
'Chuyến du lịch 2 ngày 1 đêm tại vịnh Hạ Long sẽ mang đến cho bạn những trải nghiệm tuyệt vời. Bạn sẽ được ngắm nhìn hàng nghìn hòn đảo đá vôi kỳ vĩ, thăm quan động Thiên Cung, làng chài Cửa Vạn, và thưởng thức hải sản tươi ngon. Du thuyền được trang bị đầy đủ tiện nghi hiện đại, phòng nghỉ thoải mái và dịch vụ chăm sóc chu đáo.',
2500000,
2200000,
2,
1,
20,
4,
'EASY',
'ACTIVE',
true,
'https://images.unsplash.com/photo-1528127269322-539801943592?w=800',
'["https://images.unsplash.com/photo-1528127269322-539801943592?w=400", "https://images.unsplash.com/photo-1509650460351-3c78c0dcfce4?w=400", "https://images.unsplash.com/photo-1580654712603-eb43273aff33?w=400"]',
'["Xe đưa đón", "Du thuyền 5 sao", "Bữa ăn theo chương trình", "Hướng dẫn viên", "Bảo hiểm du lịch"]',
'["Chi phí cá nhân", "Đồ uống có cồn", "Tip cho HDV và lái xe"]',
'Hủy tour trước 7 ngày: hoàn 100% phí. Hủy trước 3-6 ngày: hoàn 50% phí. Hủy trong vòng 2 ngày: không hoàn phí.',
'Khách hàng cần có giấy tờ tùy thân hợp lệ. Trẻ em dưới 2 tuổi miễn phí, từ 2-11 tuổi tính 75% giá người lớn.',
1,
NOW(),
NOW()),

-- Tour 2: Sapa Trekking
('Sapa Trekking 3 ngày 2 đêm - Fansipan', 
'Chinh phục nóc nhà Đông Dương và khám phá văn hóa dân tộc',
'Hành trình 3 ngày 2 đêm tại Sapa sẽ đưa bạn đến với những thửa ruộng bậc thang tuyệt đẹp, các bản làng dân tộc thiểu số đặc sắc. Bạn sẽ có cơ hội chinh phục đỉnh Fansipan bằng cáp treo hiện đại, trekking qua những con đường mòn thơ mộng, và tìm hiểu văn hóa độc đáo của người H''Mông, Dao đỏ.',
1800000,
1500000,
3,
2,
15,
6,
'MODERATE',
'ACTIVE',
true,
'https://images.unsplash.com/photo-1539650116574-75c0c6d73469?w=800',
'["https://images.unsplash.com/photo-1539650116574-75c0c6d73469?w=400", "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400", "https://images.unsplash.com/photo-1553150195-8383e3743b87?w=400"]',
'["Xe đưa đón", "Khách sạn 3 sao", "Vé cáp treo Fansipan", "Bữa ăn theo chương trình", "Hướng dẫn viên địa phương"]',
'["Chi phí cá nhân", "Đồ uống ngoài chương trình", "Các tour tùy chọn"]',
'Hủy tour trước 10 ngày: hoàn 90% phí. Hủy trước 5-9 ngày: hoàn 70% phí. Hủy trong vòng 4 ngày: hoàn 30% phí.',
'Tour yêu cầu sức khỏe tốt do có hoạt động trekking. Nên mang theo giày thể thao và áo ấm.',
2,
NOW(),
NOW()),

-- Tour 3: Phú Quốc Beach
('Phú Quốc 4 ngày 3 đêm - Thiên đường biển đảo', 
'Thư giãn tại bãi biển đẹp nhất Việt Nam với resort 5 sao',
'Kỳ nghỉ 4 ngày 3 đêm tại đảo ngọc Phú Quốc sẽ mang đến cho bạn những giây phút thư giãn tuyệt vời. Bạn sẽ được tắm biển tại bãi Sao, bãi Kem với làn nước trong xanh, cát trắng mịn. Thăm quan làng chài Hàm Ninh, vườn tiêu, nhà thùng nước mắm truyền thống, và khám phá các hoạt động thể thao biển hấp dẫn.',
4200000,
3800000,
4,
3,
25,
2,
'EASY',
'ACTIVE',
true,
'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
'["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400", "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400", "https://images.unsplash.com/photo-1571801208806-fe5f129e2c4d?w=400"]',
'["Vé máy bay khứ hồi", "Resort 5 sao", "Xe đưa đón sân bay", "Bữa sáng hằng ngày", "Tour 4 đảo", "Bảo hiểm du lịch"]',
'["Bữa trưa, tối", "Spa và massage", "Các hoạt động thể thao biển", "Shopping"]',
'Hủy tour trước 15 ngày: hoàn 80% phí. Hủy trước 7-14 ngày: hoàn 60% phí. Hủy trong vòng 6 ngày: hoàn 20% phí.',
'Thời gian lý tưởng: tháng 10-4. Nên mang kem chống nắng, kính râm và đồ bơi.',
3,
NOW(),
NOW()),

-- Tour 4: Đà Lạt Romantic
('Đà Lạt 3 ngày 2 đêm - Thành phố ngàn hoa', 
'Lãng mạn tại thành phố mùa xuân với khí hậu mát mẻ',
'Chuyến du lịch 3 ngày 2 đêm tại Đà Lạt sẽ đưa bạn đến với thành phố ngàn hoa thơ mộng. Thăm quan thác Elephant, hồ Xuân Hương, chùa Linh Phước, làng hoa Vạn Thành, và thưởng thức các món ăn đặc sản như bánh tráng nướng, chả cá Đà Lạt. Không khí mát mẻ quanh năm và cảnh quan lãng mạn.',
1600000,
1400000,
3,
2,
18,
4,
'EASY',
'ACTIVE',
false,
'https://images.unsplash.com/photo-1578271887552-5ac3a72752d2?w=800',
'["https://images.unsplash.com/photo-1578271887552-5ac3a72752d2?w=400", "https://images.unsplash.com/photo-1562179136-4663191ca4bb?w=400", "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=400"]',
'["Xe đưa đón", "Khách sạn 3 sao", "Bữa ăn theo chương trình", "Hướng dẫn viên", "Vé tham quan"]',
'["Chi phí cá nhân", "Đồ uống", "Mua sắm đặc sản", "Các hoạt động không trong chương trình"]',
'Hủy tour trước 5 ngày: hoàn 80% phí. Hủy trước 2-4 ngày: hoàn 50% phí. Hủy trong 1 ngày: không hoàn phí.',
'Nên mang theo áo ấm vì thời tiết mát mẻ. Thích hợp cho các cặp đôi và gia đình.',
1,
NOW(),
NOW()),

-- Tour 5: Ninh Bình Adventure
('Ninh Bình 2 ngày 1 đêm - Hoa Lư Tam Cốc', 
'Khám phá vẻ đẹp hùng vĩ của vịnh Hạ Long trên cạn',
'Tour 2 ngày 1 đêm tại Ninh Bình đưa bạn khám phá cố đô Hoa Lư, du thuyền sông Ngô Đồng qua Tam Cốc - Bích Động, leo núi Mua để ngắm toàn cảnh, và thăm Tràng An di sản thế giới. Cảnh quan núi non hùng vĩ, sông nước thơ mộng tạo nên một bức tranh thiên nhiên tuyệt đẹp.',
1200000,
1000000,
2,
1,
20,
6,
'MODERATE',
'ACTIVE',
false,
'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800',
'["https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=400", "https://images.unsplash.com/photo-1583919098097-6fa7ac5a7a32?w=400", "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=400"]',
'["Xe đưa đón", "Khách sạn 3 sao", "Thuyền thăm Tam Cốc", "Bữa ăn theo chương trình", "Vé tham quan", "Hướng dẫn viên"]',
'["Chi phí cá nhân", "Đồ uống ngoài bữa ăn", "Tip cho thuyền công", "Xe đạp cho thuê"]',
'Hủy tour trước 3 ngày: hoàn 80% phí. Hủy trước 1-2 ngày: hoàn 50% phí. Hủy cùng ngày: không hoàn phí.',
'Nên mang nón, kem chống nắng. Tour có hoạt động leo núi nên cần giày thể thao.',
2,
NOW(),
NOW()),

-- Tour 6: Mekong Delta
('Miền Tây 2 ngày 1 đêm - Chợ nổi Cái Răng', 
'Trải nghiệm cuộc sống miệt vườn và chợ nổi sông nước',
'Hành trình 2 ngày 1 đêm khám phá miền Tây Nam Bộ với chợ nổi Cái Răng, vườn trái cây, làng nghề truyền thống. Bạn sẽ được chèo thuyền trên kênh rạch, thưởng thức trái cây tươi ngon, nghe đờn ca tài tử, và tìm hiểu văn hóa sông nước đặc trưng miền Tây.',
1100000,
950000,
2,
1,
16,
8,
'EASY',
'ACTIVE',
false,
'https://images.unsplash.com/photo-1571057887532-7c2d5e8f2b9d?w=800',
'["https://images.unsplash.com/photo-1571057887532-7c2d5e8f2b9d?w=400", "https://images.unsplash.com/photo-1608736869737-8c366cf892c5?w=400", "https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=400"]',
'["Xe đưa đón", "Khách sạn 2 sao", "Thuyền thăm chợ nổi", "Bữa ăn đặc sản miền Tây", "Hướng dẫn viên"]',
'["Chi phí cá nhân", "Đồ uống", "Mua trái cây", "Tip cho chủ vườn"]',
'Hủy tour trước 3 ngày: hoàn 100% phí. Hủy trước 1-2 ngày: hoàn 70% phí. Hủy cùng ngày: hoàn 30% phí.',
'Thời gian tốt nhất: tháng 12-4 (mùa khô). Nên mang nón và kem chống nắng.',
4,
NOW(),
NOW()),

-- Tour 7: Hội An Ancient Town
('Hội An 3 ngày 2 đêm - Phố cổ và Mỹ Sơn', 
'Khám phá di sản văn hóa thế giới và ẩm thực đặc sắc',
'Tour 3 ngày 2 đêm tại Hội An đưa bạn khám phá phố cổ với kiến trúc độc đáo, đền tháp Mỹ Sơn của người Chăm, làng rau Trà Quế, và thưởng thức các món ăn nổi tiếng như cao lầu, white rose, bánh mì Phượng. Buổi tối thả đèn hoa đăng trên sông Hoài thơ mộng.',
2000000,
1750000,
3,
2,
20,
4,
'EASY',
'ACTIVE',
true,
'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800',
'["https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=400", "https://images.unsplash.com/photo-1582719471009-5a9e4bdd7af3?w=400", "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=400"]',
'["Xe đưa đón", "Khách sạn 4 sao", "Vé tham quan Mỹ Sơn", "Xe đạp tham quan phố cổ", "Bữa ăn theo chương trình", "Hướng dẫn viên"]',
'["Chi phí cá nhân", "Đồ uống", "Mua sắm", "Massage và spa", "Tour thêm"]',
'Hủy tour trước 7 ngày: hoàn 90% phí. Hủy trước 3-6 ngày: hoàn 60% phí. Hủy trong 2 ngày: hoàn 20% phí.',
'Thời gian lý tưởng: tháng 2-8. Phố cổ đông đúc vào cuối tuần và lễ hội.',
5,
NOW(),
NOW()),

-- Tour 8: Cao Bang Falls
('Cao Bằng 3 ngày 2 đêm - Thác Bản Giốc', 
'Chiêm ngưỡng thác nước hùng vĩ biên giới Việt - Trung',
'Chuyến du lịch 3 ngày 2 đêm tại Cao Bằng đưa bạn đến thác Bản Giốc - thác nước lớn nhất Việt Nam, động Ngườm Ngao kỳ vĩ, và núi Đôi độc đáo. Cảnh quan thiên nhiên hoang sơ, hùng vĩ cùng văn hóa các dân tộc thiểu số đa dạng tạo nên chuyến đi đầy ấn tượng.',
1700000,
1500000,
3,
2,
12,
6,
'MODERATE',
'DRAFT',
false,
'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
'["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400", "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=400", "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400"]',
'["Xe đưa đón", "Khách sạn 2 sao", "Bữa ăn theo chương trình", "Vé tham quan", "Thuyền tham quan thác", "Hướng dẫn viên"]',
'["Chi phí cá nhân", "Đồ uống", "Thuê xe máy", "Mua đặc sản địa phương"]',
'Hủy tour trước 5 ngày: hoàn 80% phí. Hủy trước 2-4 ngày: hoàn 50% phí. Hủy trong 1 ngày: không hoàn phí.',
'Đường đi có nhiều dốc núi, phù hợp cho người có sức khỏe tốt. Mùa đẹp nhất: tháng 9-11.',
2,
NOW(),
NOW()),

-- Tour 9: Con Dao Island
('Côn Đảo 4 ngày 3 đêm - Đảo thiêng liêng', 
'Khám phá lịch sử bi hùng và thiên nhiên hoang sơ',
'Tour 4 ngày 3 đêm tại Côn Đảo mang đến trải nghiệm đầy cảm xúc với di tích lịch sử Nhà tù Côn Đảo, mộ cô Võ Thị Sáu, và các bãi biển đẹp như Đầm Trầu, An Hải. Bạn sẽ được lặn ngắm san hô, câu cá, và thưởng thức hải sản tươi ngon trong không gian yên tĩnh, tách biệt.',
5500000,
5000000,
4,
3,
15,
4,
'MODERATE',
'INACTIVE',
false,
'https://images.unsplash.com/photo-1571801208806-fe5f129e2c4d?w=800',
'["https://images.unsplash.com/photo-1571801208806-fe5f129e2c4d?w=400", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400", "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400"]',
'["Vé máy bay khứ hồi", "Resort 4 sao", "Xe đưa đón", "Bữa ăn theo chương trình", "Tour lặn ngắm san hô", "Vé tham quan"]',
'["Đồ uống có cồn", "Spa và massage", "Hoạt động thể thao nước", "Chi phí cá nhân"]',
'Hủy tour trước 20 ngày: hoàn 70% phí. Hủy trước 10-19 ngày: hoàn 50% phí. Hủy trong 9 ngày: hoàn 20% phí.',
'Tour phụ thuộc vào thời tiết bay. Cần giấy tờ tùy thân để đi máy bay. Mùa đẹp: tháng 3-9.',
3,
NOW(),
NOW()),

-- Tour 10: Ha Giang Loop
('Hà Giang 4 ngày 3 đêm - Cung đường hạnh phúc', 
'Khám phá vẻ đẹp hoang sơ và hùng vĩ của miền núi phía Bắc',
'Hành trình 4 ngày 3 đêm tại Hà Giang sẽ đưa bạn qua cung đường hạnh phúc với các điểm đến: Quản Bạ, Yên Minh, Đồng Văn, Mèo Vạc, Má Pí Lèng. Chiêm ngưỡng cao nguyên đá Đồng Văn, cột cờ Lũng Cú, và tìm hiểu văn hóa đặc sắc của các dân tộc thiểu số.',
2200000,
2000000,
4,
3,
12,
6,
'HARD',
'DRAFT',
false,
'https://images.unsplash.com/photo-1539650116574-75c0c6d73469?w=800',
'["https://images.unsplash.com/photo-1539650116574-75c0c6d73469?w=400", "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400", "https://images.unsplash.com/photo-1553150195-8383e3743b87?w=400"]',
'["Xe máy/xe jeep", "Nhà nghỉ địa phương", "Xăng xe", "Bữa ăn theo chương trình", "Hướng dẫn viên địa phương", "Bảo hiểm"]',
'["Chi phí cá nhân", "Đồ uống có cồn", "Đồ ăn ngoài chương trình", "Tip HDV"]',
'Hủy tour trước 7 ngày: hoàn 80% phí. Hủy trước 3-6 ngày: hoàn 50% phí. Hủy trong 2 ngày: không hoàn phí.',
'Cần bằng lái xe máy A1. Đường đi khó, cần sức khỏe tốt. Mùa hoa tam giác mạch: tháng 10-11.',
2,
NOW(),
NOW());

-- Insert sample tour itineraries
INSERT INTO tour_itineraries (
    tour_id,
    day_number,
    title,
    description,
    activities,
    accommodation,
    meals,
    transportation,
    created_at,
    updated_at
) VALUES 
-- Itinerary for Tour 1: Hạ Long Bay
(1, 1, 'Hà Nội - Hạ Long - Du thuyền', 
'Khởi hành từ Hà Nội, di chuyển đến Hạ Long, check-in du thuyền và bắt đầu hành trình khám phá vịnh',
'["8:00 - Đón khách tại Hà Nội", "12:00 - Đến Hạ Long, check-in du thuyền", "13:00 - Ăn trưa trên du thuyền", "15:00 - Thăm động Thiên Cung", "17:00 - Ngắm hoàng hôn trên vịnh", "19:00 - Ăn tối và nghỉ ngơi"]',
'Du thuyền 5 sao',
'["Ăn trưa", "Ăn tối"]',
'Xe du lịch đời mới, Du thuyền',
NOW(),
NOW()),

(1, 2, 'Hạ Long - Làng chài Cửa Vạn - Hà Nội', 
'Thăm làng chài, tắm biển và trở về Hà Nội',
'["7:00 - Ăn sáng trên du thuyền", "8:30 - Thăm làng chài Cửa Vạn", "10:00 - Tắm biển tại bãi Titov", "11:30 - Trả phòng, ăn trưa", "14:00 - Về Hà Nội", "18:00 - Kết thúc tour tại Hà Nội"]',
'Du thuyền (đêm trước)',
'["Ăn sáng", "Ăn trưa"]',
'Du thuyền, Xe du lịch',
NOW(),
NOW()),

-- Itinerary for Tour 2: Sapa
(2, 1, 'Hà Nội - Sapa - Fansipan', 
'Di chuyển đến Sapa và chinh phục đỉnh Fansipan',
'["6:00 - Khởi hành từ Hà Nội", "11:00 - Đến Sapa, nghỉ ngơi", "13:00 - Ăn trưa đặc sản Sapa", "14:30 - Lên cáp treo Fansipan", "17:00 - Về khách sạn nghỉ ngơi", "19:00 - Ăn tối và khám phá chợ đêm"]',
'Khách sạn 3 sao',
'["Ăn trưa", "Ăn tối"]',
'Xe du lịch, Cáp treo',
NOW(),
NOW()),

(2, 2, 'Sapa - Bản Cát Cát - Ta Phìn', 
'Trekking khám phá các bản làng dân tộc',
'["8:00 - Ăn sáng", "9:00 - Trekking bản Cát Cát", "12:00 - Ăn trưa tại bản", "14:00 - Thăm bản Ta Phìn", "16:30 - Về Sapa nghỉ ngơi", "19:00 - Ăn tối"]',
'Khách sạn 3 sao',
'["Ăn sáng", "Ăn trưa", "Ăn tối"]',
'Đi bộ trekking',
NOW(),
NOW()),

(2, 3, 'Sapa - Hà Nội', 
'Tham quan và trở về Hà Nội',
'["8:00 - Ăn sáng", "9:00 - Thăm bản Lao Chải", "11:00 - Mua sắm đặc sản", "13:00 - Ăn trưa và khởi hành về Hà Nội", "18:00 - Về đến Hà Nội"]',
'Không',
'["Ăn sáng", "Ăn trưa"]',
'Xe du lịch',
NOW(),
NOW());

-- Insert some tour itinerary partners (linking tours with partners)
INSERT INTO tour_itinerary_partners (
    tour_itinerary_id,
    partner_id,
    partner_type,
    description,
    created_at,
    updated_at
) VALUES 
-- Tour 1 partnerships
(1, 1, 'HOTEL', 'Du thuyền 5 sao Paradise Elegance', NOW(), NOW()),
(1, 2, 'RESTAURANT', 'Nhà hàng hải sản tại du thuyền', NOW(), NOW()),
(2, 1, 'HOTEL', 'Du thuyền 5 sao Paradise Elegance', NOW(), NOW()),
(2, 2, 'RESTAURANT', 'Nhà hàng hải sản tại du thuyền', NOW(), NOW()),

-- Tour 2 partnerships  
(3, 3, 'HOTEL', 'Sapa View Hotel 3 sao', NOW(), NOW()),
(3, 4, 'RESTAURANT', 'Nhà hàng đặc sản Sapa', NOW(), NOW()),
(4, 3, 'HOTEL', 'Sapa View Hotel 3 sao', NOW(), NOW()),
(4, 4, 'RESTAURANT', 'Nhà hàng đặc sản Sapa', NOW(), NOW()),
(5, 4, 'RESTAURANT', 'Nhà hàng đặc sản Sapa', NOW(), NOW());

-- Update tour statistics (optional - for testing stats display)
-- This will be automatically calculated by the getTourStats service method

-- Sample additional data
COMMIT;
